In [ ]:
#Question 1: Which districts have the highest number of arrests and warrants?

In [3]:
import pandas as pd
from pathlib import Path

In [4]:
#File to Load
crimes_csv = Path("./Resources/Crimes_-_2001_to_Present.csv")

#Read Data FIle and Store into Pandas DataFrames
crimes_data = pd.read_csv(crimes_csv)

#Display Data Frame (ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location)
crimes_data.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10224738,HY411648,09/05/2015 01:30:00 PM,043XX S WOOD ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,...,12.0,61.0,08B,1165074.0,1875917.0,2015,02/10/2018 03:50:01 PM,41.815117,-87.670000,"(41.815117282, -87.669999562)"
1,10224739,HY411615,09/04/2015 11:30:00 AM,008XX N CENTRAL AVE,0870,THEFT,POCKET-PICKING,CTA BUS,False,False,...,29.0,25.0,06,1138875.0,1904869.0,2015,02/10/2018 03:50:01 PM,41.895080,-87.765400,"(41.895080471, -87.765400451)"
2,11646166,JC213529,09/01/2018 12:01:00 AM,082XX S INGLESIDE AVE,0810,THEFT,OVER $500,RESIDENCE,False,True,...,8.0,44.0,06,NaN,NaN,2018,04/06/2019 04:04:43 PM,NaN,NaN,NaN
3,10224740,HY411595,09/05/2015 12:45:00 PM,035XX W BARRY AVE,2023,NARCOTICS,POSS: HEROIN(BRN/TAN),SIDEWALK,True,False,...,35.0,21.0,18,1152037.0,1920384.0,2015,02/10/2018 03:50:01 PM,41.937406,-87.716650,"(41.937405765, -87.716649687)"
4,10224741,HY411610,09/05/2015 01:00:00 PM,0000X N LARAMIE AVE,0560,ASSAULT,SIMPLE,APARTMENT,False,True,...,28.0,25.0,08A,1141706.0,1900086.0,2015,02/10/2018 03:50:01 PM,41.881903,-87.755121,"(41.881903443, -87.755121152)"

In [5]:
#Display Data Frame (Date, IUCR, Primary Type, Description, Location Description, Arrest, District, FBI Code, Year, Latitude, Longitude)
crime_data = crimes_data[["Date","IUCR","Primary Type", "Description", "Location Description", "Arrest", "District", "FBI Code", "Year", "Latitude", "Longitude"]]
crime_data

,Date,IUCR,Primary Type,Description,Location Description,Arrest,District,FBI Code,Year,Latitude,Longitude
0,09/05/2015 01:30:00 PM,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,9.0,08B,2015,41.815117,-87.670000
1,09/04/2015 11:30:00 AM,0870,THEFT,POCKET-PICKING,CTA BUS,False,15.0,06,2015,41.895080,-87.765400
2,09/01/2018 12:01:00 AM,0810,THEFT,OVER $500,RESIDENCE,False,6.0,06,2018,NaN,NaN
3,09/05/2015 12:45:00 PM,2023,NARCOTICS,POSS: HEROIN(BRN/TAN),SIDEWALK,True,14.0,18,2015,41.937406,-87.716650
4,09/05/2015 01:00:00 PM,0560,ASSAULT,SIMPLE,APARTMENT,False,15.0,08A,2015,41.881903,-87.755121
...,...,...,...,...,...,...,...,...,...,...,...
3185891,10/23/2005 06:00:00 AM,1310,CRIMINAL DAMAGE,TO PROPERTY,DRUG STORE,False,6.0,14,2005,41.750491,-87.654302
3185892,10/21/2005 03:53:55 PM,0460,BATTERY,SIMPLE,OTHER COMMERCIAL TRANSPORTATION,False,15.0,08B,2005,41.902186,-87.761660
3185893,10/23/2005 12:00:00 PM,2820,OTHER OFFENSE,TELEPHONE THREAT,RESIDENCE,False,3.0,26,2005,41.762318,-87.597577
3185894,10/23/2005 11:25:00 AM,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,24.0,14,2005,41.997641,-87.695070
3185895,10/21/2005 07:00:00 AM,0620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,22.0,05,2005,41.702310,-87.600000

In [27]:
crime_data.astype({"Arrest": str}).dtypes
crime_data.dtypes

Date                     object
IUCR                     object
Primary Type             object
Description              object
Location Description     object
Arrest                     bool
District                float64
FBI Code                 object
Year                      int64
Latitude                float64
Longitude               float64
dtype: object

In [6]:
#Drop Rows where Year <2015
crime_data_filteredyears = crime_data[crime_data["Year"] >= 2015]

#Drop Rows where Arrest = False
arrests_df = crime_data_filteredyears[crime_data_filteredyears["Arrest"] == True]

#Another Resource for no arrests
noarrests_df = crime_data_filteredyears[crime_data_filteredyears["Arrest"] == False]

In [28]:
crime_years = crime_data_filteredyears.sort_values(by=['District',"Primary Type", "Year"], ascending=True)
crime_years = crime_years.sort_values(by = ["Arrest"], ascending = False)
crime_years = crime_years.set_index(["District", "Primary Type", "Arrest"])

#crime_years = crime_years.set_
crime_years

crime_years.to_csv("Crimes_2015toPresent.csv")

In [7]:
# Group by District and find the maximum number of arrests
highest_arrests_per_district = crime_data_filteredyears.groupby("District")["Primary Type"].sum().reset_index()

# Sort the DataFrame by the number of arrests in descending order
#highest_arrests_per_district = highest_arrests_per_district.sort_values(by='Arrest', ascending=False)

# Display DataFrame
highest_arrests_per_district

    District                                       Primary Type
0        1.0  THEFTTHEFTTHEFTTHEFTTHEFTTHEFTCRIMINAL DAMAGET...
1        2.0  BATTERYTHEFTCRIMINAL DAMAGETHEFTTHEFTMOTOR VEH...
2        3.0  ROBBERYWEAPONS VIOLATIONTHEFTOTHER OFFENSECRIM...
3        4.0  BURGLARYCRIMINAL DAMAGECRIMINAL DAMAGECRIMINAL...
4        5.0  OTHER OFFENSENARCOTICSBATTERYBURGLARYBATTERYTH...
5        6.0  THEFTBURGLARYBATTERYBATTERYNARCOTICSASSAULTCRI...
6        7.0  BATTERYNARCOTICSTHEFTCRIMINAL DAMAGEBATTERYBAT...
7        8.0  DECEPTIVE PRACTICETHEFTOTHER OFFENSETHEFTDECEP...
8        9.0  BATTERYTHEFTTHEFTDECEPTIVE PRACTICETHEFTPUBLIC...
9       10.0  THEFTOTHER OFFENSETHEFTMOTOR VEHICLE THEFTBATT...
10      11.0  BURGLARYNARCOTICSWEAPONS VIOLATIONDECEPTIVE PR...
11      12.0  ROBBERYTHEFTBATTERYTHEFTNARCOTICSCRIMINAL DAMA...
12      14.0  NARCOTICSBURGLARYTHEFTCRIMINAL DAMAGEMOTOR VEH...
13      15.0  THEFTASSAULTCRIMINAL DAMAGEWEAPONS VIOLATIONCR...
14      16.0  BATTERYBATTERYCRIMINAL DAMAGEBURGLARYTHEFTBURG...
15      17.0  ASSAULTOTHER OFFENSECRIMINAL DAMAGEOTHER OFFEN...
16      18.0  DECEPTIVE PRACTICETHEFTTHEFTTHEFTBATTERYBATTER...
17      19.0  CRIMINAL TRESPASSMOTOR VEHICLE THEFTBURGLARYTH...
18      20.0  ROBBERYTHEFTCRIMINAL DAMAGEASSAULTASSAULTTHEFT...
19      22.0  BURGLARYTHEFTBATTERYBATTERYNARCOTICSCRIMINAL D...
20      24.0  THEFTMOTOR VEHICLE THEFTASSAULTBATTERYTHEFTTHE...
21      25.0  WEAPONS VIOLATIONOTHER OFFENSEBATTERYTHEFTTHEF...
22      31.0  DECEPTIVE PRACTICEDECEPTIVE PRACTICEDECEPTIVE ...

In [12]:
#school_name = school_data_complete.set_index("school_name").groupby(["school_name"])
arrests_true = crimes_data.set_index("Arrest").groupby(["Arrest"])
arrests_true

In [11]:
#ninth_graders = school_data_complete[(school_data_complete["grade"] == "9th")]
arrests_true = crimes_data[(crimes_data]
arrests_true

Empty DataFrame
Columns: [ID, Case Number, Date, Block, IUCR, Primary Type, Description, Location Description, Arrest, Domestic, Beat, District, Ward, Community Area, FBI Code, X Coordinate, Y Coordinate, Year, Updated On, Latitude, Longitude, Location]
Index: []

[0 rows x 22 columns]